//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.GravarPedido {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.senior.com.br", ConfigurationName="GravarPedido.sapiens_Synccom_senior_g5_co_cafeeira_pedidosvenda")]
    public interface sapiens_Synccom_senior_g5_co_cafeeira_pedidosvenda {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_Synccom_senior_g5_co_cafeeira_pedidosvenda/" +
            "GravarPedidoRequest", ReplyAction="http://services.senior.com.br/sapiens_Synccom_senior_g5_co_cafeeira_pedidosvenda/" +
            "GravarPedidoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        adminlte.GravarPedido.pedidosvendaGravarPedidoOut GravarPedido(string user, string password, int encryption, adminlte.GravarPedido.pedidosvendaGravarPedidoIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_Synccom_senior_g5_co_cafeeira_pedidosvenda/" +
            "GravarPedidoRequest", ReplyAction="http://services.senior.com.br/sapiens_Synccom_senior_g5_co_cafeeira_pedidosvenda/" +
            "GravarPedidoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<adminlte.GravarPedido.pedidosvendaGravarPedidoOut> GravarPedidoAsync(string user, string password, int encryption, adminlte.GravarPedido.pedidosvendaGravarPedidoIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_Synccom_senior_g5_co_cafeeira_pedidosvenda/" +
            "RelatoriosRequest", ReplyAction="http://services.senior.com.br/sapiens_Synccom_senior_g5_co_cafeeira_pedidosvenda/" +
            "RelatoriosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        adminlte.GravarPedido.pedidosvendaRelatoriosOut Relatorios(string user, string password, int encryption, adminlte.GravarPedido.pedidosvendaRelatoriosIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_Synccom_senior_g5_co_cafeeira_pedidosvenda/" +
            "RelatoriosRequest", ReplyAction="http://services.senior.com.br/sapiens_Synccom_senior_g5_co_cafeeira_pedidosvenda/" +
            "RelatoriosResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<adminlte.GravarPedido.pedidosvendaRelatoriosOut> RelatoriosAsync(string user, string password, int encryption, adminlte.GravarPedido.pedidosvendaRelatoriosIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_Synccom_senior_g5_co_cafeeira_pedidosvenda/" +
            "TrocarFilialRequest", ReplyAction="http://services.senior.com.br/sapiens_Synccom_senior_g5_co_cafeeira_pedidosvenda/" +
            "TrocarFilialResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        adminlte.GravarPedido.pedidosvendaTrocarFilialOut TrocarFilial(string user, string password, int encryption, adminlte.GravarPedido.pedidosvendaTrocarFilialIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_Synccom_senior_g5_co_cafeeira_pedidosvenda/" +
            "TrocarFilialRequest", ReplyAction="http://services.senior.com.br/sapiens_Synccom_senior_g5_co_cafeeira_pedidosvenda/" +
            "TrocarFilialResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<adminlte.GravarPedido.pedidosvendaTrocarFilialOut> TrocarFilialAsync(string user, string password, int encryption, adminlte.GravarPedido.pedidosvendaTrocarFilialIn parameters);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class pedidosvendaGravarPedidoIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        private pedidosvendaGravarPedidoInPedido[] pedidoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pedido", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public pedidosvendaGravarPedidoInPedido[] pedido {
            get {
                return this.pedidoField;
            }
            set {
                this.pedidoField = value;
                this.RaisePropertyChanged("pedido");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class pedidosvendaGravarPedidoInPedido : object, System.ComponentModel.INotifyPropertyChanged {
        
        private pedidosvendaGravarPedidoInPedidoAvalistas[] avalistasField;
        
        private string cifFobField;
        
        private string codCliField;
        
        private string codConField;
        
        private string codCpgField;
        
        private string codEmpField;
        
        private string codFilField;
        
        private string codFpgField;
        
        private string codGreField;
        
        private string codRepField;
        
        private string codTraField;
        
        private string codUsuField;
        
        private string datEmiField;
        
        private string fecPedField;
        
        private string horEmiField;
        
        private string numPedField;
        
        private string opeExeField;
        
        private pedidosvendaGravarPedidoInPedidoParcelas[] parcelasField;
        
        private string plaVeiField;
        
        private pedidosvendaGravarPedidoInPedidoProduto[] produtoField;
        
        private string sitPedField;
        
        private string temParField;
        
        private string tnsProField;
        
        private string uSU_AcrFinField;
        
        private string uSU_ObsEntField;
        
        private string uSU_ObsPedField;
        
        private string uSU_TxaJurField;
        
        private string vlrDarField;
        
        private string vlrFreField;
        
        private string vlrLiqField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("avalistas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public pedidosvendaGravarPedidoInPedidoAvalistas[] avalistas {
            get {
                return this.avalistasField;
            }
            set {
                this.avalistasField = value;
                this.RaisePropertyChanged("avalistas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string cifFob {
            get {
                return this.cifFobField;
            }
            set {
                this.cifFobField = value;
                this.RaisePropertyChanged("cifFob");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string codCli {
            get {
                return this.codCliField;
            }
            set {
                this.codCliField = value;
                this.RaisePropertyChanged("codCli");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string codCon {
            get {
                return this.codConField;
            }
            set {
                this.codConField = value;
                this.RaisePropertyChanged("codCon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string codCpg {
            get {
                return this.codCpgField;
            }
            set {
                this.codCpgField = value;
                this.RaisePropertyChanged("codCpg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string codEmp {
            get {
                return this.codEmpField;
            }
            set {
                this.codEmpField = value;
                this.RaisePropertyChanged("codEmp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string codFil {
            get {
                return this.codFilField;
            }
            set {
                this.codFilField = value;
                this.RaisePropertyChanged("codFil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string codFpg {
            get {
                return this.codFpgField;
            }
            set {
                this.codFpgField = value;
                this.RaisePropertyChanged("codFpg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string codGre {
            get {
                return this.codGreField;
            }
            set {
                this.codGreField = value;
                this.RaisePropertyChanged("codGre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string codRep {
            get {
                return this.codRepField;
            }
            set {
                this.codRepField = value;
                this.RaisePropertyChanged("codRep");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string codTra {
            get {
                return this.codTraField;
            }
            set {
                this.codTraField = value;
                this.RaisePropertyChanged("codTra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string codUsu {
            get {
                return this.codUsuField;
            }
            set {
                this.codUsuField = value;
                this.RaisePropertyChanged("codUsu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string datEmi {
            get {
                return this.datEmiField;
            }
            set {
                this.datEmiField = value;
                this.RaisePropertyChanged("datEmi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string fecPed {
            get {
                return this.fecPedField;
            }
            set {
                this.fecPedField = value;
                this.RaisePropertyChanged("fecPed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public string horEmi {
            get {
                return this.horEmiField;
            }
            set {
                this.horEmiField = value;
                this.RaisePropertyChanged("horEmi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public string numPed {
            get {
                return this.numPedField;
            }
            set {
                this.numPedField = value;
                this.RaisePropertyChanged("numPed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=16)]
        public string opeExe {
            get {
                return this.opeExeField;
            }
            set {
                this.opeExeField = value;
                this.RaisePropertyChanged("opeExe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parcelas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public pedidosvendaGravarPedidoInPedidoParcelas[] parcelas {
            get {
                return this.parcelasField;
            }
            set {
                this.parcelasField = value;
                this.RaisePropertyChanged("parcelas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=18)]
        public string plaVei {
            get {
                return this.plaVeiField;
            }
            set {
                this.plaVeiField = value;
                this.RaisePropertyChanged("plaVei");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("produto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=19)]
        public pedidosvendaGravarPedidoInPedidoProduto[] produto {
            get {
                return this.produtoField;
            }
            set {
                this.produtoField = value;
                this.RaisePropertyChanged("produto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=20)]
        public string sitPed {
            get {
                return this.sitPedField;
            }
            set {
                this.sitPedField = value;
                this.RaisePropertyChanged("sitPed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=21)]
        public string temPar {
            get {
                return this.temParField;
            }
            set {
                this.temParField = value;
                this.RaisePropertyChanged("temPar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=22)]
        public string tnsPro {
            get {
                return this.tnsProField;
            }
            set {
                this.tnsProField = value;
                this.RaisePropertyChanged("tnsPro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=23)]
        public string USU_AcrFin {
            get {
                return this.uSU_AcrFinField;
            }
            set {
                this.uSU_AcrFinField = value;
                this.RaisePropertyChanged("USU_AcrFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=24)]
        public string USU_ObsEnt {
            get {
                return this.uSU_ObsEntField;
            }
            set {
                this.uSU_ObsEntField = value;
                this.RaisePropertyChanged("USU_ObsEnt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=25)]
        public string USU_ObsPed {
            get {
                return this.uSU_ObsPedField;
            }
            set {
                this.uSU_ObsPedField = value;
                this.RaisePropertyChanged("USU_ObsPed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=26)]
        public string USU_TxaJur {
            get {
                return this.uSU_TxaJurField;
            }
            set {
                this.uSU_TxaJurField = value;
                this.RaisePropertyChanged("USU_TxaJur");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=27)]
        public string vlrDar {
            get {
                return this.vlrDarField;
            }
            set {
                this.vlrDarField = value;
                this.RaisePropertyChanged("vlrDar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=28)]
        public string vlrFre {
            get {
                return this.vlrFreField;
            }
            set {
                this.vlrFreField = value;
                this.RaisePropertyChanged("vlrFre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=29)]
        public string vlrLiq {
            get {
                return this.vlrLiqField;
            }
            set {
                this.vlrLiqField = value;
                this.RaisePropertyChanged("vlrLiq");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class pedidosvendaGravarPedidoInPedidoAvalistas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> codAvaField;
        
        private bool codAvaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> codAva {
            get {
                return this.codAvaField;
            }
            set {
                this.codAvaField = value;
                this.RaisePropertyChanged("codAva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codAvaSpecified {
            get {
                return this.codAvaFieldSpecified;
            }
            set {
                this.codAvaFieldSpecified = value;
                this.RaisePropertyChanged("codAvaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class pedidosvendaTrocarFilialOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string erroExecucaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string erroExecucao {
            get {
                return this.erroExecucaoField;
            }
            set {
                this.erroExecucaoField = value;
                this.RaisePropertyChanged("erroExecucao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class pedidosvendaTrocarFilialIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codEmpField;
        
        private string codFilField;
        
        private string codUsuField;
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string codEmp {
            get {
                return this.codEmpField;
            }
            set {
                this.codEmpField = value;
                this.RaisePropertyChanged("codEmp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string codFil {
            get {
                return this.codFilField;
            }
            set {
                this.codFilField = value;
                this.RaisePropertyChanged("codFil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string codUsu {
            get {
                return this.codUsuField;
            }
            set {
                this.codUsuField = value;
                this.RaisePropertyChanged("codUsu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class pedidosvendaRelatoriosOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string erroExecucaoField;
        
        private string logProcessoField;
        
        private string retornoBase64Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string erroExecucao {
            get {
                return this.erroExecucaoField;
            }
            set {
                this.erroExecucaoField = value;
                this.RaisePropertyChanged("erroExecucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string logProcesso {
            get {
                return this.logProcessoField;
            }
            set {
                this.logProcessoField = value;
                this.RaisePropertyChanged("logProcesso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string retornoBase64 {
            get {
                return this.retornoBase64Field;
            }
            set {
                this.retornoBase64Field = value;
                this.RaisePropertyChanged("retornoBase64");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class pedidosvendaRelatoriosIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> codEmpField;
        
        private bool codEmpFieldSpecified;
        
        private System.Nullable<int> codFilField;
        
        private bool codFilFieldSpecified;
        
        private string codMdrField;
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        private System.Nullable<int> numPedField;
        
        private bool numPedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> codEmp {
            get {
                return this.codEmpField;
            }
            set {
                this.codEmpField = value;
                this.RaisePropertyChanged("codEmp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codEmpSpecified {
            get {
                return this.codEmpFieldSpecified;
            }
            set {
                this.codEmpFieldSpecified = value;
                this.RaisePropertyChanged("codEmpSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<int> codFil {
            get {
                return this.codFilField;
            }
            set {
                this.codFilField = value;
                this.RaisePropertyChanged("codFil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codFilSpecified {
            get {
                return this.codFilFieldSpecified;
            }
            set {
                this.codFilFieldSpecified = value;
                this.RaisePropertyChanged("codFilSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string codMdr {
            get {
                return this.codMdrField;
            }
            set {
                this.codMdrField = value;
                this.RaisePropertyChanged("codMdr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public System.Nullable<int> numPed {
            get {
                return this.numPedField;
            }
            set {
                this.numPedField = value;
                this.RaisePropertyChanged("numPed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numPedSpecified {
            get {
                return this.numPedFieldSpecified;
            }
            set {
                this.numPedFieldSpecified = value;
                this.RaisePropertyChanged("numPedSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class pedidosvendaGravarPedidoOutRespostaPedidoGridPro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codEmpField;
        
        private string codFilField;
        
        private string numPedField;
        
        private string retornoField;
        
        private string seqIpdField;
        
        private string sitIpdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string codEmp {
            get {
                return this.codEmpField;
            }
            set {
                this.codEmpField = value;
                this.RaisePropertyChanged("codEmp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string codFil {
            get {
                return this.codFilField;
            }
            set {
                this.codFilField = value;
                this.RaisePropertyChanged("codFil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string numPed {
            get {
                return this.numPedField;
            }
            set {
                this.numPedField = value;
                this.RaisePropertyChanged("numPed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
                this.RaisePropertyChanged("retorno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string seqIpd {
            get {
                return this.seqIpdField;
            }
            set {
                this.seqIpdField = value;
                this.RaisePropertyChanged("seqIpd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string sitIpd {
            get {
                return this.sitIpdField;
            }
            set {
                this.sitIpdField = value;
                this.RaisePropertyChanged("sitIpd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class pedidosvendaGravarPedidoOutRespostaPedidoGridPar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codEmpField;
        
        private string codFilField;
        
        private string numPedField;
        
        private string retornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string codEmp {
            get {
                return this.codEmpField;
            }
            set {
                this.codEmpField = value;
                this.RaisePropertyChanged("codEmp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string codFil {
            get {
                return this.codFilField;
            }
            set {
                this.codFilField = value;
                this.RaisePropertyChanged("codFil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string numPed {
            get {
                return this.numPedField;
            }
            set {
                this.numPedField = value;
                this.RaisePropertyChanged("numPed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
                this.RaisePropertyChanged("retorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class pedidosvendaGravarPedidoOutRespostaPedidoGridObs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codEmpField;
        
        private string codFilField;
        
        private string numPedField;
        
        private string retornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string codEmp {
            get {
                return this.codEmpField;
            }
            set {
                this.codEmpField = value;
                this.RaisePropertyChanged("codEmp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string codFil {
            get {
                return this.codFilField;
            }
            set {
                this.codFilField = value;
                this.RaisePropertyChanged("codFil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string numPed {
            get {
                return this.numPedField;
            }
            set {
                this.numPedField = value;
                this.RaisePropertyChanged("numPed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
                this.RaisePropertyChanged("retorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class pedidosvendaGravarPedidoOutRespostaPedido : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codEmpField;
        
        private string codFilField;
        
        private pedidosvendaGravarPedidoOutRespostaPedidoGridObs[] gridObsField;
        
        private pedidosvendaGravarPedidoOutRespostaPedidoGridPar[] gridParField;
        
        private pedidosvendaGravarPedidoOutRespostaPedidoGridPro[] gridProField;
        
        private string msgRetField;
        
        private string numPedField;
        
        private string pedBloField;
        
        private string retornoField;
        
        private string sitPedField;
        
        private string tipPedField;
        
        private string tipRetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string codEmp {
            get {
                return this.codEmpField;
            }
            set {
                this.codEmpField = value;
                this.RaisePropertyChanged("codEmp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string codFil {
            get {
                return this.codFilField;
            }
            set {
                this.codFilField = value;
                this.RaisePropertyChanged("codFil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("gridObs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public pedidosvendaGravarPedidoOutRespostaPedidoGridObs[] gridObs {
            get {
                return this.gridObsField;
            }
            set {
                this.gridObsField = value;
                this.RaisePropertyChanged("gridObs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("gridPar", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public pedidosvendaGravarPedidoOutRespostaPedidoGridPar[] gridPar {
            get {
                return this.gridParField;
            }
            set {
                this.gridParField = value;
                this.RaisePropertyChanged("gridPar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("gridPro", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public pedidosvendaGravarPedidoOutRespostaPedidoGridPro[] gridPro {
            get {
                return this.gridProField;
            }
            set {
                this.gridProField = value;
                this.RaisePropertyChanged("gridPro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string msgRet {
            get {
                return this.msgRetField;
            }
            set {
                this.msgRetField = value;
                this.RaisePropertyChanged("msgRet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string numPed {
            get {
                return this.numPedField;
            }
            set {
                this.numPedField = value;
                this.RaisePropertyChanged("numPed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string pedBlo {
            get {
                return this.pedBloField;
            }
            set {
                this.pedBloField = value;
                this.RaisePropertyChanged("pedBlo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
                this.RaisePropertyChanged("retorno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string sitPed {
            get {
                return this.sitPedField;
            }
            set {
                this.sitPedField = value;
                this.RaisePropertyChanged("sitPed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string tipPed {
            get {
                return this.tipPedField;
            }
            set {
                this.tipPedField = value;
                this.RaisePropertyChanged("tipPed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string tipRet {
            get {
                return this.tipRetField;
            }
            set {
                this.tipRetField = value;
                this.RaisePropertyChanged("tipRet");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class pedidosvendaGravarPedidoOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string erroExecucaoField;
        
        private string mensagemRetornoField;
        
        private pedidosvendaGravarPedidoOutRespostaPedido[] respostaPedidoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string erroExecucao {
            get {
                return this.erroExecucaoField;
            }
            set {
                this.erroExecucaoField = value;
                this.RaisePropertyChanged("erroExecucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string mensagemRetorno {
            get {
                return this.mensagemRetornoField;
            }
            set {
                this.mensagemRetornoField = value;
                this.RaisePropertyChanged("mensagemRetorno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("respostaPedido", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public pedidosvendaGravarPedidoOutRespostaPedido[] respostaPedido {
            get {
                return this.respostaPedidoField;
            }
            set {
                this.respostaPedidoField = value;
                this.RaisePropertyChanged("respostaPedido");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class pedidosvendaGravarPedidoInPedidoProduto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codDepField;
        
        private string codDerField;
        
        private string codProField;
        
        private string codTprField;
        
        private string datEntField;
        
        private string opeExeField;
        
        private string perAcrField;
        
        private string perDscField;
        
        private string preUniField;
        
        private string qtdPedField;
        
        private string seqIpdField;
        
        private string uSU_DatDscField;
        
        private string uSU_HorDscField;
        
        private string uSU_PreBasField;
        
        private string uSU_UsuDscField;
        
        private string vlrAcrField;
        
        private string vlrDscField;
        
        private string vlrFreField;
        
        private string vlrLiqField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string codDep {
            get {
                return this.codDepField;
            }
            set {
                this.codDepField = value;
                this.RaisePropertyChanged("codDep");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string codDer {
            get {
                return this.codDerField;
            }
            set {
                this.codDerField = value;
                this.RaisePropertyChanged("codDer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string codPro {
            get {
                return this.codProField;
            }
            set {
                this.codProField = value;
                this.RaisePropertyChanged("codPro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string codTpr {
            get {
                return this.codTprField;
            }
            set {
                this.codTprField = value;
                this.RaisePropertyChanged("codTpr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string datEnt {
            get {
                return this.datEntField;
            }
            set {
                this.datEntField = value;
                this.RaisePropertyChanged("datEnt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string opeExe {
            get {
                return this.opeExeField;
            }
            set {
                this.opeExeField = value;
                this.RaisePropertyChanged("opeExe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string perAcr {
            get {
                return this.perAcrField;
            }
            set {
                this.perAcrField = value;
                this.RaisePropertyChanged("perAcr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string perDsc {
            get {
                return this.perDscField;
            }
            set {
                this.perDscField = value;
                this.RaisePropertyChanged("perDsc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string preUni {
            get {
                return this.preUniField;
            }
            set {
                this.preUniField = value;
                this.RaisePropertyChanged("preUni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string qtdPed {
            get {
                return this.qtdPedField;
            }
            set {
                this.qtdPedField = value;
                this.RaisePropertyChanged("qtdPed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string seqIpd {
            get {
                return this.seqIpdField;
            }
            set {
                this.seqIpdField = value;
                this.RaisePropertyChanged("seqIpd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string USU_DatDsc {
            get {
                return this.uSU_DatDscField;
            }
            set {
                this.uSU_DatDscField = value;
                this.RaisePropertyChanged("USU_DatDsc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string USU_HorDsc {
            get {
                return this.uSU_HorDscField;
            }
            set {
                this.uSU_HorDscField = value;
                this.RaisePropertyChanged("USU_HorDsc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string USU_PreBas {
            get {
                return this.uSU_PreBasField;
            }
            set {
                this.uSU_PreBasField = value;
                this.RaisePropertyChanged("USU_PreBas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public string USU_UsuDsc {
            get {
                return this.uSU_UsuDscField;
            }
            set {
                this.uSU_UsuDscField = value;
                this.RaisePropertyChanged("USU_UsuDsc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public string vlrAcr {
            get {
                return this.vlrAcrField;
            }
            set {
                this.vlrAcrField = value;
                this.RaisePropertyChanged("vlrAcr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=16)]
        public string vlrDsc {
            get {
                return this.vlrDscField;
            }
            set {
                this.vlrDscField = value;
                this.RaisePropertyChanged("vlrDsc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public string vlrFre {
            get {
                return this.vlrFreField;
            }
            set {
                this.vlrFreField = value;
                this.RaisePropertyChanged("vlrFre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=18)]
        public string vlrLiq {
            get {
                return this.vlrLiqField;
            }
            set {
                this.vlrLiqField = value;
                this.RaisePropertyChanged("vlrLiq");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class pedidosvendaGravarPedidoInPedidoParcelas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string opeExeField;
        
        private string perParField;
        
        private string seqParField;
        
        private string vctParField;
        
        private string vlrParField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string opeExe {
            get {
                return this.opeExeField;
            }
            set {
                this.opeExeField = value;
                this.RaisePropertyChanged("opeExe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string perPar {
            get {
                return this.perParField;
            }
            set {
                this.perParField = value;
                this.RaisePropertyChanged("perPar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string seqPar {
            get {
                return this.seqParField;
            }
            set {
                this.seqParField = value;
                this.RaisePropertyChanged("seqPar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string vctPar {
            get {
                return this.vctParField;
            }
            set {
                this.vctParField = value;
                this.RaisePropertyChanged("vctPar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string vlrPar {
            get {
                return this.vlrParField;
            }
            set {
                this.vlrParField = value;
                this.RaisePropertyChanged("vlrPar");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface sapiens_Synccom_senior_g5_co_cafeeira_pedidosvendaChannel : adminlte.GravarPedido.sapiens_Synccom_senior_g5_co_cafeeira_pedidosvenda, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sapiens_Synccom_senior_g5_co_cafeeira_pedidosvendaClient : System.ServiceModel.ClientBase<adminlte.GravarPedido.sapiens_Synccom_senior_g5_co_cafeeira_pedidosvenda>, adminlte.GravarPedido.sapiens_Synccom_senior_g5_co_cafeeira_pedidosvenda {
        
        public sapiens_Synccom_senior_g5_co_cafeeira_pedidosvendaClient() {
        }
        
        public sapiens_Synccom_senior_g5_co_cafeeira_pedidosvendaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public sapiens_Synccom_senior_g5_co_cafeeira_pedidosvendaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sapiens_Synccom_senior_g5_co_cafeeira_pedidosvendaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sapiens_Synccom_senior_g5_co_cafeeira_pedidosvendaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public adminlte.GravarPedido.pedidosvendaGravarPedidoOut GravarPedido(string user, string password, int encryption, adminlte.GravarPedido.pedidosvendaGravarPedidoIn parameters) {
            return base.Channel.GravarPedido(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<adminlte.GravarPedido.pedidosvendaGravarPedidoOut> GravarPedidoAsync(string user, string password, int encryption, adminlte.GravarPedido.pedidosvendaGravarPedidoIn parameters) {
            return base.Channel.GravarPedidoAsync(user, password, encryption, parameters);
        }
        
        public adminlte.GravarPedido.pedidosvendaRelatoriosOut Relatorios(string user, string password, int encryption, adminlte.GravarPedido.pedidosvendaRelatoriosIn parameters) {
            return base.Channel.Relatorios(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<adminlte.GravarPedido.pedidosvendaRelatoriosOut> RelatoriosAsync(string user, string password, int encryption, adminlte.GravarPedido.pedidosvendaRelatoriosIn parameters) {
            return base.Channel.RelatoriosAsync(user, password, encryption, parameters);
        }
        
        public adminlte.GravarPedido.pedidosvendaTrocarFilialOut TrocarFilial(string user, string password, int encryption, adminlte.GravarPedido.pedidosvendaTrocarFilialIn parameters) {
            return base.Channel.TrocarFilial(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<adminlte.GravarPedido.pedidosvendaTrocarFilialOut> TrocarFilialAsync(string user, string password, int encryption, adminlte.GravarPedido.pedidosvendaTrocarFilialIn parameters) {
            return base.Channel.TrocarFilialAsync(user, password, encryption, parameters);
        }
    }
}
